out/production/Exam3GitHub/objects/Product_Table__c.object
<CustomObject>
    <description>Provides information about the products that will be placed in the shopping cart for later ordering.</description>
    <fields>
        <fullName>Added_Date__c</fullName>
        <label>Added Date</label>
        <type>Date</type>
    </fields>
    <label>Product Table</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductControllerTest.cls
@isTest
public class ProductControllerTest {
    @testSetup
    static void methodName() {
        insert new Org_Configuration__c(Period_Term__c = 10);
    }
    @IsTest public static void testGetProduct() {
        Product_Table__c prod = new Product_Table__c (Name = 'TestPhone', Added_Date__c = System.today());
        insert prod;
        Test.startTest();
        PageReference pageRef = Page.Product;
        pageRef.getParameters().put('id', String.valueOf(prod.Id));
        Test.setCurrentPage(pageRef);

        ProductController testController = new ProductController();
        System.assertEquals(prod.Id, testController.product.Id);


        Test.stopTest();
    }
    @isTest
    public static void testBuck (){
        Product_Table__c prod = new Product_Table__c (Name = 'TestPhone', Added_Date__c = System.today());
        insert prod;

        Test.startTest();
        PageReference pageRef = Page.Product;
        pageRef.getParameters().put('id', String.valueOf(prod.Id));
        pageRef.getParameters().put('returnPage','ProductList');
        Test.setCurrentPage(pageRef);

        BuyProductController testController = new BuyProductController();
        PageReference newPage = testController.back();
        System.assertEquals('/apex/ProductList', newPage.getUrl());

        Test.stopTest();

    }
}